spring.application.name=universidad

server.port=8086

# SQL Server
app.sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=universidad_db;encrypt=false;trustServerCertificate=true
app.sqlserver.username=sa
app.sqlserver.password=SqlServer1234!
app.sqlserver.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# MariaDB
app.mariadb.url=jdbc:mariadb://localhost:3307/universidad
app.mariadb.username=root
app.mariadb.password=Root1234
app.mariadb.driver=org.mariadb.jdbc.Driver
