spring.application.name=universidad

server.port=8086

# MySQL (BD 1: Estudiante - Contenedor mysql-dbeaver)
app.mysql.url=jdbc:mysql://localhost:3308/universidad?useSSL=false&allowPublicKeyRetrieval=true
app.mysql.username=root
app.mysql.password=Root1234
app.mysql.driver=com.mysql.cj.jdbc.Driver

# SQL Server (BD 2: Carrera_Universidad - Contenedor sqlserver-dbeaver)
app.sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=universidad_db;encrypt=false;trustServerCertificate=true
app.sqlserver.username=sa
app.sqlserver.password=SqlServer1234!
app.sqlserver.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# PostgreSQL Local Docker (BD 3: Matrícula - Contenedor postgres-dbeaver)
app.postgres.url=jdbc:postgresql://localhost:5432/universidad
app.postgres.username=postgres
app.postgres.password=Postgres1234!
app.postgres.driver=org.postgresql.Driver